# Generated by Django 5.0.3 on 2024-03-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0026_userprofile_custom_css"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="default_home_link",
            field=models.CharField(
                choices=[("", ""), ("!unread", "Unread")], default="", max_length=20
            ),
        ),
    ]
