# Generated by Django 5.0.3 on 2024-03-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0027_userprofile_default_home_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="default_home_link",
            field=models.CharField(
                choices=[("none", "All"), ("unread", "Unread")],
                default="none",
                max_length=20,
            ),
        ),
    ]
