# Generated by Django 5.0.3 on 2024-03-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0027_userprofile_bookmark_description_display_and_more"),
        ("bookmarks", "0028_alter_userprofile_default_home_link"),
    ]

    operations = []
