# Generated by Django 5.0.3 on 2024-04-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0029_merge_20240327_1847"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bookmarks_per_page",
            field=models.CharField(
                choices=[("15", "15"), ("30", "30"), ("60", "60")],
                default="30",
                max_length=10,
            ),
        ),
    ]
